image: node:8

pages:
  stage: deploy
  script:
  - npm install
  - node --max-old-space-size=4096 node_modules/@angular/cli/bin/ng build --prod --aot --source-map --no-progress --base-href /loneliness-scale/
  # To the browser and to the world it's /loneliness-scale/, but to GitLab CI it must be "public".
  - mv dist/loneliness-scale public
  # Compression.
  - find public -name '*.html' -exec gzip -k -9 \{\} \;
  - find public -name '*.js' -exec gzip -k -9 \{\} \;
  - find public -name '*.js.map' -exec gzip -k -9 \{\} \;
  # Helps us debug the CI deployment issues.
  - ls -laF public
  artifacts:
    paths:
    # The name of the directory must be "public", cf. https://gitlab.com/gitlab-org/gitlab-ce/issues/40686.
    - public
  only:
  - master
